package br.ufc.virtual.smd.oqcomer.model;

import br.ufc.virtual.smd.oqcomer.R;

public class DataBase {

    public static int[] banners = {
            R.drawable.banner_1,
            R.drawable.banner_2,
            R.drawable.banner_3,
            R.drawable.bolo_chocolate,
            R.drawable.brigadeiro,
            R.drawable.brownie,
            R.drawable.cachorro_quente,
            R.drawable.cajuina,
            R.drawable.camarao,
            R.drawable.coxinha,
            R.drawable.empada,
            R.drawable.escondidinho_carnedosol,
            R.drawable.hamburguer,
            R.drawable.kalzonekalzone,
            R.drawable.misto_quente,
            R.drawable.ohmydog,
            R.drawable.palha_italiana,
            R.drawable.pao_de_queijo,
            R.drawable.pastel_de_queijo,
            R.drawable.picanha,
            R.drawable.pizzahut_peperoni,
            R.drawable.po_de_guarana,
            R.drawable.rock_burguer,
            R.drawable.salada_fruta,
            R.drawable.self_service_fisica,
            R.drawable.sushi_oxente,
            R.drawable.torta_frango,
            R.drawable.vitamina_acai

    };
    public static String[] foodNames = {
            "Pastel de requeijão com carne seca",
            "Nachos mechicanos a moda da casa",
            "Escondidinho de camarão",
            "Bolo de chocolate",
            "Brigadeiro",
            "Brownie de chocolate",
            "Cachorro quente",
            "Cajuina de verdade",
            "Camarão alho e óleo",
            "Coxinha",
            "Empada",
            "Escondidinho de carne do sol",
            "Hamburguer",
            "Kalzone de calabresa",
            "Misto quente",
            "Oh my dog peperoni",
            "Palha italiana",
            "Pão de queijo",
            "Pastel de queijo",
            "Picanha com batatas",
            "Pizza de peperoni",
            "Pó de guaraná",
            "Rock burger",
            "Salada de frutas",
            "Self service",
            "Sushis variados",
            "Torta de frango",
            "Vitamina de Açai"
    };
    public static String[] restaurantLocal = {
            "Dom Pastel",
            "Floresta Gourmet",
            "Florence l'escale",
            "Cantina da Química",
            "Cantina da Tia Jô",
            "Cantina da SEARA de Ciências",
            "Cantina da Tia Jô",
            "Cantina da Química",
            "Cantina da Tia Jô",
            "Cantina da Geologia",
            "Cantina da Eng. de Pesca",
            "Cantina da Física",
            "Cantina da Geologia",
            "Kalzone",
            "Cantina da SEARA de Ciências",
            "Oh my dog",
            "Cantina da Tia Jô",
            "Cantina da Química",
            "Cantina da Tia Jô",
            "Restaurante Alex",
            "Pizza Hut",
            "Ponto da Vitamina",
            "Rock And Burgers",
            "Cantina da Tia Jô",
            "Cantina da Física",
            "Oxente oriente",
            "Cantina da Química",
            "Cantina da Eng. de Pesca"
    };
    public static String[] localDistances = {
            "0,6 Km",
            "1,1 Km",
            "0,8 Km",
            "0,6 Km",
            "1,1 Km",
            "0,8 Km",
            "0,6 Km",
            "1,1 Km",
            "0,8 Km",
            "0,6 Km",
            "1,1 Km",
            "0,8 Km",
            "0,6 Km",
            "1,1 Km",
            "0,8 Km",
            "0,6 Km",
            "1,1 Km",
            "0,8 Km",
            "0,6 Km",
            "1,1 Km",
            "0,8 Km",
            "0,6 Km",
            "1,1 Km",
            "0,8 Km",
            "0,6 Km",
            "1,1 Km",
            "0,8 Km",
            "0,6 Km"
    };
    public static String[] countComments = {
            "15",
            "41",
            "18",
            "15",
            "41",
            "18",
            "15",
            "41",
            "18",
            "15",
            "41",
            "18",
            "15",
            "41",
            "18",
            "15",
            "41",
            "18",
            "15",
            "41",
            "18",
            "15",
            "41",
            "18",
            "15",
            "41",
            "18",
            "15"
    };
    public static int[] satisfactionFlags = {
            R.drawable.very_good_flag,
            R.drawable.the_best_flag,
            R.drawable.great_flag,
            R.drawable.very_good_flag,
            R.drawable.the_best_flag,
            R.drawable.great_flag,
            R.drawable.very_good_flag,
            R.drawable.the_best_flag,
            R.drawable.great_flag,
            R.drawable.very_good_flag,
            R.drawable.the_best_flag,
            R.drawable.great_flag,
            R.drawable.very_good_flag,
            R.drawable.the_best_flag,
            R.drawable.great_flag,
            R.drawable.very_good_flag,
            R.drawable.the_best_flag,
            R.drawable.great_flag,
            R.drawable.very_good_flag,
            R.drawable.the_best_flag,
            R.drawable.great_flag,
            R.drawable.very_good_flag,
            R.drawable.the_best_flag,
            R.drawable.great_flag,
            R.drawable.very_good_flag,
            R.drawable.the_best_flag,
            R.drawable.great_flag,
            R.drawable.very_good_flag,
    };

    public static String[] foodDescriptions = {
            "",
            "",
            "",
            "O bolo de chocolate com a cobertura e recheio de chocolate mais delicioso que você vai provar.",
            "Muitas variedades de docinhos na cantina, mas o brigadeiro se destaca entre as melhores opções.",
            "Para os apaixonados em chocolate esse brownie é a pedida certa de sobremesa.",
            "Simples mas que mata aquela fome, esse é o cachorro quente da cantina da tia Jô. Sempre bem recheado.",
            "A bebida a base de caju é uma opção para aqueles que não tomam refrigerante, vale experimentar.",
            "Uma ótima escolha no self service da cantina no horário de almoço, vale a pena conferir.",
            "Com os mais variados recheios de coxinha o tradicional frango é o mais pedido, que é uma especialidade da cantina.",
            "Uma empada bem recheada e da massa sequinha e temperada. Um dos produtos mais vendidoda cantina e referência do local.",
            "Um dos pratos típicos da região que faz muito sucesso na cantina, e sempre no ponto certo.",
            "Simples mas que mata aquela fome, esse é o sanduiche da cantina da geologia, sempre bem recheado.",
            "Um lanche rápido e bem recheado de calabresa, feito com uma massa de forno.",
            "Feito na hora o misto quente dessa cantina têm tudo para lhe conquistar.",
            "Esse é para quem tem coragem. Cachorro quente com peperoni e queijo por cima, é bastante picante e muito delicioso.",
            "Uma das melhores sobremesas da cantina, cobreta por leite em pó e recheio de chocolate, a sobremesa vai lhe encantar.",
            "O melhor pãozinho de queijo do campus do PICI. Sempre bem crocantes e quentinhos por fora e macio por dentro. É uma cantina com uma boa variedade de produtos.",
            "Pastel com a massa crocante e sequinha, recheado com queijo. A cantina possui outras opções de pastéis e lanches, vale apena visitar.",
            "Uma das melhores pedidas do restaurante, muito bem temperada e saborosa essa picanha.",
            "Simples mente a pizza de peperoni mais gostosa de todas, recheio e molho na medidas certas.",
            "Pó de guaraná batido com gelo, leite, castanha e limão. Um dos mais completos e vitaminados do campus do PICI.",
            "Um sanduíche bem recheado e cheio de personalidade, combinando bem com o ambiente.",
            "Com uma boa variedade em sua salada de frutas, a sobremesa é bastante pedida na cantina.",
            "Um self service cheio de opções e sempre muito boas.",
            "Uma ótima escolha de jantar, os combinados de sushi são sempre uma boa opção além de sempre fresquinhos por serem feitos na hora.",
            "Uma torta salgada recheada com frango e queijo, feita com massa de empada, uma dos melhores salgados da cantina.",
            "Vitamina de açai batida com leite e misturada com granola e banana. E a cantina é uma das melhores da universidade e uma das mais ventiladas."
    };

    public static String[] restaurantDescriptions = {
            "",
            "",
            "",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
            "Av. Bezerra de Menezes, 2450 - São Gerardo, Fortaleza - CE",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
            "Av. Bezerra de Menezes, 259 - Farias Brito, Fortaleza - CE",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
            "R. Gustavo Sampaio, 1951 - Parquelândia,Fortaleza - CE",
            "Av. Bezerra de Menezes, 2450 - São Gerardo, Fortaleza - CE",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
            "Av. Bezerra de Menezes, 1655 - São Gerardo, Fortaleza - CE",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
            "Av. Bezerra de Menezes, 510 - São Gerardo, Fortaleza - CE",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
            "Universidade Federal do Ceará, Campus do Pici - Fortaleza-CE",
    };

    public static String[] foodOpinions = {
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana.",
            "João Paulo L. - 03/05/2015 20:30:00\n\nÓtimo serviço e um preço bacana."
    };

    public static int[] foodSatisfactionImage = {
            R.drawable.very_good_icon,
            R.drawable.the_best_icon,
            R.drawable.great_icon,
            R.drawable.very_good_icon,
            R.drawable.the_best_icon,
            R.drawable.great_icon,
            R.drawable.very_good_icon,
            R.drawable.the_best_icon,
            R.drawable.great_icon,
            R.drawable.very_good_icon,
            R.drawable.the_best_icon,
            R.drawable.great_icon,
            R.drawable.very_good_icon,
            R.drawable.the_best_icon,
            R.drawable.great_icon,
            R.drawable.very_good_icon,
            R.drawable.the_best_icon,
            R.drawable.great_icon,
            R.drawable.very_good_icon,
            R.drawable.the_best_icon,
            R.drawable.great_icon,
            R.drawable.very_good_icon,
            R.drawable.the_best_icon,
            R.drawable.great_icon,
            R.drawable.very_good_icon,
            R.drawable.the_best_icon,
            R.drawable.great_icon,
            R.drawable.very_good_icon,
    };
}
